#!/bin/bash

PROC_NAME='deepin-diskmanager-service'

/usr/bin/deepin-diskmanager-service-bin &

while [ "1" ]
do
    ProcNumber=`pidof $PROC_NAME`
    if [ $ProcNumber ];then
        deepin-diskmanager
        break;
    fi
done