#!/bin/bash

PROC_UI_BIN=`pidof deepin-diskmanager`
if [ $PROC_UI_BIN ];then
    deepin-diskmanager
    exit
fi

PROC_NAME='deepin-diskmanager-service'

/usr/bin/deepin-diskmanager-service-bin &

while [ "1" ]
do  
    ProcNumber=`pidof $PROC_NAME`
    if [ $ProcNumber ];then
        deepin-diskmanager
        break;
    fi
done

